# Generated by Django 5.2 on 2026-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_alumnos', models.IntegerField()),
                ('tipo_curso', models.CharField(max_length=100)),
            ],
        ),
    ]
